/**
 * Environment File Writer
 *
 * Writes environment variables to files in worktree directories.
 * Supports the full environment variable hierarchy.
 */

import { eq } from 'drizzle-orm';
import { promises as fs } from 'fs';
import path from 'path';
import type { Database } from '../db/client';
import { select } from '../db/database-wrapper';
import { repos, worktrees } from '../db/schema';
import type { RepoID, UserID, WorktreeID } from '../types';
import {
  getRepoIdForWorktree,
  resolveRepoEnvironment,
  resolveUserEnvironment,
  resolveUserRepoEnvironment,
  resolveWorktreeEnvironment,
} from './env-resolver';

/**
 * Metadata for the env file header
 */
interface EnvFileMetadata {
  worktreeName: string;
  repoSlug: string;
  worktreeId: string;
}

/**
 * Result of writing an env file
 */
export interface WriteEnvFileResult {
  fileName: string;
  filePath: string;
  variableCount: number;
}

/**
 * Format environment variables as .env file content
 *
 * Generates a well-formatted .env file with:
 * - Header comments with metadata
 * - Variables grouped by source layer
 * - Proper escaping of values
 */
export function formatEnvFile(
  envVars: Record<string, string>,
  layers: {
    repo?: Record<string, string>;
    userGlobal?: Record<string, string>;
    userRepo?: Record<string, string>;
    worktree?: Record<string, string>;
  },
  metadata: EnvFileMetadata
): string {
  const lines: string[] = [];
  const now = new Date().toISOString();

  // Header
  lines.push('# =====================================================');
  lines.push('# Agor Environment Variables');
  lines.push(`# Generated: ${now}`);
  lines.push(`# Worktree: ${metadata.worktreeName}`);
  lines.push(`# Repo: ${metadata.repoSlug}`);
  lines.push(`# Worktree ID: ${metadata.worktreeId}`);
  lines.push('# =====================================================');
  lines.push('');
  lines.push('# WARNING: This file is auto-generated by Agor.');
  lines.push('# Changes may be overwritten when regenerated.');
  lines.push('');

  // Track which keys have been written to avoid duplicates
  const writtenKeys = new Set<string>();

  // Helper to write a section
  const writeSection = (title: string, vars: Record<string, string> | undefined) => {
    if (!vars || Object.keys(vars).length === 0) return;

    const keysToWrite = Object.keys(vars).filter((key) => !writtenKeys.has(key));
    if (keysToWrite.length === 0) return;

    lines.push(`# --- ${title} ---`);
    for (const key of keysToWrite.sort()) {
      const value = envVars[key]; // Use merged value
      if (value !== undefined) {
        // Escape special characters in values
        const escapedValue = escapeEnvValue(value);
        lines.push(`${key}=${escapedValue}`);
        writtenKeys.add(key);
      }
    }
    lines.push('');
  };

  // Write sections in priority order (low to high)
  // Later sections won't duplicate keys from earlier sections
  writeSection('Repo Default Variables', layers.repo);
  writeSection('User Global Variables', layers.userGlobal);
  writeSection('User Repo Variables', layers.userRepo);
  writeSection('Worktree Variables', layers.worktree);

  return lines.join('\n');
}

/**
 * Escape special characters in .env file values
 */
function escapeEnvValue(value: string): string {
  // If value contains special characters, wrap in quotes
  if (
    value.includes(' ') ||
    value.includes('"') ||
    value.includes("'") ||
    value.includes('\n') ||
    value.includes('$') ||
    value.includes('\\') ||
    value.includes('#')
  ) {
    // Use double quotes and escape internal special chars
    const escaped = value
      .replace(/\\/g, '\\\\')
      .replace(/"/g, '\\"')
      .replace(/\$/g, '\\$')
      .replace(/\n/g, '\\n');
    return `"${escaped}"`;
  }
  return value;
}

/**
 * Get the env file name for a repo
 */
export async function getRepoEnvFileName(repoId: RepoID, db: Database): Promise<string | null> {
  const row = await select(db).from(repos).where(eq(repos.repo_id, repoId)).one();

  if (!row?.data || typeof row.data !== 'object') {
    return '.env';
  }

  const data = row.data as { env_file_name?: string };
  return data.env_file_name || '.env';
}

/**
 * Write environment variables to a file in the worktree directory
 *
 * @param worktreePath - Absolute path to the worktree directory
 * @param fileName - Name of the env file (e.g., '.env', '.env.local')
 * @param envVars - Merged environment variables
 * @param layers - Environment variables by layer (for formatting)
 * @param metadata - Metadata for the file header
 * @returns Result with file path and variable count
 */
export async function writeEnvFile(
  worktreePath: string,
  fileName: string,
  envVars: Record<string, string>,
  layers: {
    repo?: Record<string, string>;
    userGlobal?: Record<string, string>;
    userRepo?: Record<string, string>;
    worktree?: Record<string, string>;
  },
  metadata: EnvFileMetadata
): Promise<WriteEnvFileResult> {
  const content = formatEnvFile(envVars, layers, metadata);
  const filePath = path.join(worktreePath, fileName);

  await fs.writeFile(filePath, content, 'utf8');

  return {
    fileName,
    filePath,
    variableCount: Object.keys(envVars).length,
  };
}

/**
 * Write environment variables file for a worktree
 *
 * Resolves the full environment variable hierarchy and writes to a file.
 *
 * @param worktreeId - Worktree ID
 * @param userId - User ID (optional, for user-specific env vars)
 * @param db - Database instance
 * @returns Result with file path and variable count, or null if no env_file_name configured
 */
export async function writeWorktreeEnvFile(
  worktreeId: WorktreeID,
  userId: UserID | undefined,
  db: Database
): Promise<WriteEnvFileResult | null> {
  // Get worktree data
  const worktreeRow = await select(db)
    .from(worktrees)
    .where(eq(worktrees.worktree_id, worktreeId))
    .one();

  if (!worktreeRow) {
    throw new Error(`Worktree not found: ${worktreeId}`);
  }

  const worktreeData = worktreeRow.data as { path: string };
  const worktreePath = worktreeData.path;

  // Get repo ID
  const repoId = await getRepoIdForWorktree(worktreeId, db);
  if (!repoId) {
    throw new Error(`Repo not found for worktree: ${worktreeId}`);
  }

  // Get repo data for env_file_name and slug
  const repoRow = await select(db).from(repos).where(eq(repos.repo_id, repoId)).one();
  if (!repoRow) {
    throw new Error(`Repo not found: ${repoId}`);
  }

  const repoData = repoRow.data as { env_file_name?: string };
  const envFileName = repoData.env_file_name || '.env';

  // Resolve all layers
  const layers = {
    repo: await resolveRepoEnvironment(repoId, db),
    userGlobal: userId ? await resolveUserEnvironment(userId, db) : {},
    userRepo: userId ? await resolveUserRepoEnvironment(userId, repoId, db) : {},
    worktree: await resolveWorktreeEnvironment(worktreeId, db),
  };

  // Merge in priority order
  const merged = {
    ...layers.repo,
    ...layers.userGlobal,
    ...layers.userRepo,
    ...layers.worktree,
  };

  // Write the file
  return writeEnvFile(worktreePath, envFileName, merged, layers, {
    worktreeName: worktreeRow.name,
    repoSlug: repoRow.slug,
    worktreeId: worktreeId,
  });
}

/**
 * Read the current env file content from a worktree
 *
 * @param worktreeId - Worktree ID
 * @param db - Database instance
 * @returns File content or null if file doesn't exist or no env_file_name configured
 */
export async function readWorktreeEnvFile(
  worktreeId: WorktreeID,
  db: Database
): Promise<{ fileName: string; filePath: string; content: string } | null> {
  // Get worktree data
  const worktreeRow = await select(db)
    .from(worktrees)
    .where(eq(worktrees.worktree_id, worktreeId))
    .one();

  if (!worktreeRow) {
    return null;
  }

  const worktreeData = worktreeRow.data as { path: string };
  const worktreePath = worktreeData.path;

  // Get repo ID and env file name
  const repoId = await getRepoIdForWorktree(worktreeId, db);
  if (!repoId) {
    return null;
  }

  const envFileName = await getRepoEnvFileName(repoId, db);
  if (!envFileName) {
    return null;
  }

  const filePath = path.join(worktreePath, envFileName);

  try {
    const content = await fs.readFile(filePath, 'utf8');
    return { fileName: envFileName, filePath, content };
  } catch {
    // File doesn't exist
    return null;
  }
}
